### PR TITLE
Made documents downloadable

### PR DESCRIPTION
**Pull request by TKFRvisionOfficial**

### CODE REVIEW

**Comment by TKFRvisionOfficial** [comment]
This is extremly slow for some reason and during a download around 4 cores of my computer are at 100%. (Yes, this also happens in a release build...)

**Comment by TKFRvisionOfficial** [comment]
I have just removed all my static content code and switched to tower already working implementation. This works perfectly and is way easier to manage.

**Comment by tanneberger** [comment]
This pull request adds the `/static` route should the pdfs be served over this endpoint ? or what is it intended use ? @TKFRvisionOfficial

**Comment by MarcelCoding** [comment]
The PDFs should be served but neither the file system path nor the http path is correct.

**Review by MarcelCoding — APPROVED** [review]

**Pull request merged**
